const NI_SERVICE_ENG_APP = "NI_SERVICE_ENG_APP"
const LOCAL_FILE_PATH = "http://localhost:3000/"
const SERVER_FILE_PATH = "http://13.49.111.133:3000/"

module.exports ={
    NI_SERVICE_ENG_APP : NI_SERVICE_ENG_APP,
    LOCAL_FILE_PATH : LOCAL_FILE_PATH,
    SERVER_FILE_PATH : SERVER_FILE_PATH
}